INSERT IGNORE INTO role (id, name) VALUES (1, 'ROLE_USER');
INSERT IGNORE INTO role (id, name) VALUES (2, 'ROLE_MANAGER');
INSERT IGNORE INTO role (id, name) VALUES (3, 'ROLE_ADMIN');
INSERT IGNORE INTO role (id, name) VALUES (4, 'ROLE_DRIVER');
